name: simplexmq
version: 0.4.1
synopsis: SimpleXMQ message broker
description:  |
  This package includes <./docs/Simplex-Messaging-Server.html server>,
  <./docs/Simplex-Messaging-Client.html client> and
  <./docs/Simplex-Messaging-Agent.html agent> for SMP protocols:
  .
  * <https://github.com/simplex-chat/simplexmq/blob/master/protocol/simplex-messaging.md SMP protocol>
  * <https://github.com/simplex-chat/simplexmq/blob/master/protocol/agent-protocol.md SMP agent protocol>
  .
  See <https://github.com/simplex-chat/simplex-chat terminal chat prototype> built with SimpleXMQ broker.

homepage: https://github.com/simplex-chat/simplexmq#readme
license: AGPL-3
author: simplex.chat
maintainer: chat@simplex.chat
copyright: 2020 simplex.chat
category: Chat, Network, Web, System, Cryptography
extra-source-files:
  - README.md
  - CHANGELOG.md
  - migrations/*.*

dependencies:
  - ansi-terminal >= 0.8 && < 0.12
  - asn1-encoding == 0.9.*
  - asn1-types == 0.3.*
  - async == 2.2.*
  - attoparsec == 0.13.*
  - base >= 4.7 && < 5
  - base64-bytestring >= 1.0 && < 1.3
  - bytestring == 0.10.*
  - composition == 1.0.*
  - constraints >= 0.10 && < 0.14
  - containers >= 0.5 && < 0.7
  - cryptonite >= 0.25 && < 0.30
  - direct-sqlite == 2.3.*
  - directory == 1.3.*
  - file-embed >= 0.0.10.0 && <= 0.0.15.0
  - filepath == 1.4.*
  - generic-random >= 1.2 && < 1.5
  - iso8601-time == 0.1.*
  - memory >= 0.14 && < 0.16
  - mtl == 2.2.*
  - network >= 2.6 && < 3.2
  - network-transport == 0.5.*
  - QuickCheck >= 2.11 && < 2.15
  - random >= 1.1 && < 1.3
  - simple-logger == 0.0.4
  - sqlite-simple == 0.4.*
  - stm >= 2.4 && < 2.6
  - template-haskell >= 2.13 && < 2.17
  - text == 1.2.*
  - time >= 1.8 && < 1.10
  - transformers == 0.5.*
  - unliftio == 0.2.*
  - unliftio-core >= 0.1 && < 0.3
  - websockets == 0.12.*
  - x509 == 1.7.*

library:
  source-dirs: src

executables:
  smp-server:
    source-dirs: apps/smp-server
    main: Main.hs
    dependencies:
      - cryptostore == 0.2.*
      - ini >= 0.3 && < 0.5 
      - optparse-applicative >= 0.14 && < 0.17
      - simplexmq
    ghc-options:
      - -threaded

  smp-agent:
    source-dirs: apps/smp-agent
    main: Main.hs
    dependencies:
      - simplexmq
    ghc-options:
      - -threaded

tests:
  smp-server-test:
    source-dirs: tests
    main: Test.hs
    dependencies:
      - simplexmq
      - hspec >= 2.5 && < 2.8
      - hspec-core >= 2.5 && < 2.8
      - HUnit == 1.6.*
      - QuickCheck >= 2.11 && < 2.15
      - timeit == 2.0.*

ghc-options:
  # - -haddock
  - -Wall
  - -Wcompat
  - -Werror=incomplete-patterns
  - -Wredundant-constraints
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wunused-type-patterns
